"use client";
import { Copy, Printer, Share2, Download, FileText } from "lucide-react";
import React, { useState } from "react";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";

interface ExportResultsPanelProps {
  targetId?: string;
  fileName?: string;
}

export function ExportResultsPanel({ targetId = "calculator-export-target", fileName = "nexus-results" }: ExportResultsPanelProps) {
  const [isExporting, setIsExporting] = useState(false);
  const [showEmbedModal, setShowEmbedModal] = useState(false);
  const [embedCode, setEmbedCode] = useState("");

  const handleEmbed = () => {
    // Generate embed URL
    const url = new URL(window.location.href);
    const pathParts = url.pathname.split('/');
    // e.g. /en/calculators/mortgage-calculator -> /en/embed/calculators/mortgage-calculator
    const lang = pathParts[1];
    const category = pathParts[2];
    const slug = pathParts[3];
    const embedUrl = `${url.origin}/${lang}/embed/${category}/${slug}`;
    
    setEmbedCode(`<iframe src="${embedUrl}" width="100%" height="800" frameborder="0" allowfullscreen style="border: 1px solid #e2e8f0; border-radius: 12px; box-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.1);"></iframe>`);
    setShowEmbedModal(true);
  };

  const copyEmbedCode = () => {
    navigator.clipboard.writeText(embedCode);
    alert("Embed code copied!");
  };

  const handlePrint = () => {
    window.print();
  };
  
  const handleExportPDF = async () => {
    if (!targetId) return;
    const element = document.getElementById(targetId);
    if (!element) {
      console.warn("Export target not found");
      return;
    }

    try {
      setIsExporting(true);
      
      // Temporarily modify styles for better PDF rendering
      element.classList.add("pdf-exporting");
      
      const canvas = await html2canvas(element, {
        scale: 2, // Higher quality
        useCORS: true,
        logging: false,
        backgroundColor: document.documentElement.classList.contains('dark') ? '#0f172a' : '#ffffff', // match dark/light mode bg
      } as any);
      
      element.classList.remove("pdf-exporting");

      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
      });

      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = (canvas.height * pdfWidth) / canvas.width;
      
      let heightLeft = pdfHeight;
      let position = 0;
      
      // Add a header
      pdf.setFontSize(10);
      pdf.setTextColor(150);
      pdf.text('Generated by NexusCalculator.net', 10, 10);
      
      // Add first page
      pdf.addImage(imgData, 'PNG', 0, 15, pdfWidth, pdfHeight);
      heightLeft -= pdf.internal.pageSize.getHeight();

      // Add subsequent pages if the content is long
      while (heightLeft >= 0) {
        position = heightLeft - pdfHeight;
        pdf.addPage();
        pdf.addImage(imgData, 'PNG', 0, position, pdfWidth, pdfHeight);
        heightLeft -= pdf.internal.pageSize.getHeight();
      }

      pdf.save(`${fileName}.pdf`);
    } catch (err) {
      console.error("Error generating PDF:", err);
      alert("Failed to generate PDF. Please try printing instead.");
    } finally {
      setIsExporting(false);
    }
  };

  const handleShare = async () => {
    try {
      if (navigator.share) {
        await navigator.share({
          title: document.title,
          url: window.location.href,
        });
      } else {
        await navigator.clipboard.writeText(window.location.href);
        alert("Link copied to clipboard!");
      }
    } catch (err) {
      console.log("Error sharing:", err);
    }
  };

  return (
    <div className="flex flex-wrap items-center gap-3 p-4 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl mt-6 print:hidden">
      <span className="text-sm font-semibold text-slate-600 dark:text-slate-400 mr-2">Save & Share:</span>
      
      <button 
        onClick={handleExportPDF}
        disabled={isExporting}
        className="flex items-center gap-2 px-4 py-2 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-700 dark:text-slate-200 rounded-lg text-sm font-medium hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors shadow-sm focus:outline-none focus:ring-2 focus:ring-red-500 disabled:opacity-50"
        title="Download as PDF Document"
      >
        <FileText className={`w-4 h-4 text-red-600 ${isExporting ? 'animate-pulse' : ''}`} />
        {isExporting ? 'Generating...' : 'Export PDF'}
      </button>

      <button 
        onClick={handlePrint}
        className="flex items-center gap-2 px-4 py-2 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-700 dark:text-slate-200 rounded-lg text-sm font-medium hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors shadow-sm focus:outline-none focus:ring-2 focus:ring-emerald-500"
        title="Print using browser dialog"
      >
        <Printer className="w-4 h-4 text-emerald-600" />
        Print
      </button>

      <button 
        onClick={handleShare}
        className="flex items-center gap-2 px-4 py-2 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-700 dark:text-slate-200 rounded-lg text-sm font-medium hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
      >
        <Share2 className="w-4 h-4 text-blue-600" />
        Share
      </button>

      <button 
        onClick={handleEmbed}
        className="flex items-center gap-2 px-4 py-2 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-700 dark:text-slate-200 rounded-lg text-sm font-medium hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors shadow-sm focus:outline-none focus:ring-2 focus:ring-purple-500"
      >
        <Copy className="w-4 h-4 text-purple-600" />
        Embed Widget
      </button>

      {/* Embed Modal */}
      {showEmbedModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50 backdrop-blur-sm p-4">
          <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl shadow-xl max-w-lg w-full overflow-hidden">
            <div className="p-6 border-b border-slate-100 dark:border-slate-800 flex justify-between items-center">
              <h3 className="text-xl font-bold text-slate-900 dark:text-white">Embed this Calculator</h3>
              <button onClick={() => setShowEmbedModal(false)} className="text-slate-400 hover:text-slate-600 dark:hover:text-slate-300">
                ✕
              </button>
            </div>
            <div className="p-6 space-y-4">
              <p className="text-sm text-slate-600 dark:text-slate-400">
                Copy and paste the HTML code below to embed this calculator seamlessly on your own website.
              </p>
              <textarea 
                readOnly
                value={embedCode}
                className="w-full h-32 p-3 bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 rounded-lg text-sm font-mono text-slate-800 dark:text-slate-300 resize-none focus:outline-none focus:ring-2 focus:ring-purple-500"
              />
              <button 
                onClick={copyEmbedCode}
                className="w-full py-3 bg-purple-600 hover:bg-purple-700 text-white rounded-xl font-bold transition-colors"
              >
                Copy Embed Code
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
