import { ToolConfig } from './types';

export const fakeUserDataGeneratorConfig: ToolConfig = {
  slug: "fake-user-data-generator",
  title: "Fake User Data Generator",
  shortDescription: "Generate random, privacy-safe fake user data for database seeding, UI mockups, and API testing. Export to JSON, CSV, SQL, XML, and YAML.",
  category: "Generators",
  keywords: [
    "fake user generator", "dummy data generator", "mock data generator", 
    "random identity generator", "database seeder", "API mock data",
    "test data generation", "fake profiles", "JSON user generator", "SQL seeder"
  ],
  
  longDescription: `
**The Fake User Data Generator** is an advanced developer utility designed specifically for generating fictional, highly-structured profile data. It allows frontend engineers, backend developers, and QA testers to instantly generate realistic placeholder records for local development, UI prototyping, database seeding, and automated API testing.

> **Privacy Notice:** All data generated by this tool is strictly randomly generated algorithms using predefined dictionaries of common fictional names, streets, and domains. It never scrapes real identities, and all generated outputs are labeled as "Fake / Demo / Testing Data Only."

### Why Developers Need Fake Data

When building complex applications, relying on real user data is often dangerous, illegal, or practically impossible due to modern privacy laws like GDPR and CCPA. Furthermore, using "John Doe 1", "John Doe 2" in a UI mockup rarely stress-tests layout constraints accurately. High-quality fake data solves these problems by providing:
- **Variable Length Inputs:** Realistic names and addresses stress-test CSS flexbox layouts, text wrapping, and truncation logic.
- **Privacy Compliance:** Developers can seed a local PostgreSQL or MongoDB instance with thousands of records without risking a catastrophic PII (Personally Identifiable Information) leak.
- **API Mocking:** Frontend developers can design robust state management systems and handle pagination long before the backend API is fully implemented.

### Powerful Export Formats

A great dummy data generator must integrate seamlessly into your workflow. This tool provides instant, one-click exports into the formats developers use daily:
1. **JSON Arrays:** The standard format for REST API mocking and NoSQL document databases like MongoDB or Firebase.
2. **SQL INSERT Statements:** Ready-to-execute scripts for relational databases like PostgreSQL, MySQL, and SQLite, perfectly formatting string escaping and date types.
3. **CSV (Comma-Separated Values):** Ideal for importing into Excel, Google Sheets, or traditional BI/analytics software for data science testing.
4. **YAML & XML:** Useful for legacy system integration or specific configuration-as-code deployments.

### Localized & Themed Data

Global applications require localized testing. A UI that looks perfect with brief English names might break completely when displaying lengthy German compound words or complex French addresses. Our generator supports multiple localized modes:
- **United States & Canada:** Standard state abbreviations, Zip/Postal codes, and regional phone number formats.
- **European Locales (UK, France, Germany, Spain):** Localized first and last names, postal formats, and internationalized phone dial codes.
- **Asian Locales (India, Bangladesh):** Region-specific name patterns and administrative districts.
- **Random Global Mode:** A stress-test mode that mixes formats to ensure your application can handle truly international user bases.

### Seamless Database Seeding

Manually writing database seeds is tedious. With our tool, you can toggle the exact fields your schema requires (e.g., omitting "Website" but including "Avatar" and "Date of Birth"), set the bulk generation slider to 100 users, and instantly download a \`.sql\` file. The tool automatically handles single quotes and syntax formatting, allowing you to drop the script straight into your database client and populate your staging environment in seconds.

### Ensuring Safety and Security

It is critical that developers never use real user data in testing environments. Staging databases are frequently less secure than production environments and are common targets for data breaches. By adopting a strict "Fake Data Only" policy for development, teams drastically reduce their liability footprint while simultaneously improving the quality of their automated testing suites.
  `,

  features: [
    "Bulk generate up to 100+ fictional user profiles instantly",
    "Support for 8+ localized regions including US, UK, Germany, France, India, and Bangladesh",
    "Export seamlessly to JSON, CSV, SQL INSERT, XML, and YAML formats",
    "Granular field toggles: enable or disable emails, passwords, avatars, addresses, and bios",
    "Advanced password generator integration (strong, mixed symbols, custom lengths)",
    "API mock mode for generating nested JSON structures and GraphQL-like objects",
    "High-quality placeholder avatar generation (UI gradients and initials)",
    "Persistent local history and seed-based generation for reproducible tests",
    "Interactive, responsive table view with instant search and filtering",
    "One-click clipboard copy and file download for generated datasets"
  ],

  useCases: [
    "Seeding local development databases (PostgreSQL, MySQL, MongoDB) with bulk realistic mock data",
    "Creating fake JSON payloads for frontend development before backend REST APIs are ready",
    "Stress-testing CSS grids, tables, and typography layouts with variable-length names and addresses",
    "Populating staging environments for QA and automated end-to-end (E2E) testing frameworks like Cypress or Playwright",
    "Designing high-fidelity UI prototypes requiring realistic avatars, job titles, and biographies"
  ],

  howToSteps: [
    "Select the desired 'Locale' from the sidebar to localize names, addresses, and phone numbers.",
    "Use the slider to choose the 'Amount' of fake users you want to generate (e.g., 10 or 100).",
    "Toggle the specific data fields your application schema requires (Name, Email, Password, Avatar, etc).",
    "Select your preferred Export Format (JSON, SQL, CSV, XML, YAML) from the dropdown.",
    "Click the 'Generate' button to instantly create the dataset.",
    "Preview the data in the responsive table, or use the tabs to view the raw code structure.",
    "Use the 'Copy' or 'Download' buttons to export the data into your project."
  ],

  examples: [
    {
      title: "JSON REST API Response",
      description: "Generating a mock user profile in JSON format.",
      input: "Format: JSON | Fields: Name, Email, Job",
      output: '[\n  {\n    "id": "e4f8d9c2",\n    "name": "Jane Smith",\n    "email": "jane.smith@example-demo.com",\n    "jobTitle": "Frontend Engineer"\n  }\n]'
    },
    {
      title: "SQL INSERT Script",
      description: "Generating database seeding scripts.",
      input: "Format: SQL | Amount: 2",
      output: "INSERT INTO users (id, name, email)\nVALUES \n('a1b2', 'Alex Chen', 'alex@test-domain.net'),\n('c3d4', 'Sarah Jones', 'sarah.j@mock-site.org');"
    },
    {
      title: "CSV Export",
      description: "Generating comma-separated data for spreadsheet import.",
      input: "Format: CSV | Fields: Username, Phone",
      output: "username,phone\nfast_runner_99,+1-555-019-2834\ntech_guru,+1-555-882-9111"
    }
  ],

  faq: [
    {
      question: "What is a fake user data generator?",
      answer: "A fake user data generator is a developer tool that creates randomized, realistic-looking (but entirely fictional) profile information like names, emails, and addresses. It is used to populate applications during development without exposing real user data."
    },
    {
      question: "Why should developers use fake data?",
      answer: "Using fake data protects privacy, complies with laws like GDPR, and prevents sensitive data leaks if a staging database is compromised. It also allows developers to stress-test their UI layouts with varied string lengths and formats."
    },
    {
      question: "Is the generated data real?",
      answer: "No. The data is 100% fictional. It is algorithmically generated using dictionaries of common names, randomized numbers, and reserved safe domains (like example.com). It does not scrape real identities."
    },
    {
      question: "Can fake data be used for automated testing?",
      answer: "Absolutely. Fake data is highly recommended for end-to-end (E2E) testing frameworks like Cypress, Selenium, or Playwright to ensure tests are reproducible and safe."
    },
    {
      question: "Is this tool safe to use?",
      answer: "Yes. All data generation happens locally in your browser. No data is sent to our servers, and the outputs are inherently safe, non-identifiable mockups."
    },
    {
      question: "Can I export fake data to SQL?",
      answer: "Yes, the tool features a dedicated SQL export mode. It automatically generates valid 'INSERT INTO' statements and handles string escaping, making it perfect for seeding PostgreSQL, MySQL, and SQLite databases."
    },
    {
      question: "How do API developers use mock data?",
      answer: "Before a backend database is connected, frontend developers use JSON mock data to build out UI components, handle asynchronous loading states, and program pagination logic as if the real API existed."
    },
    {
      question: "Why avoid using real user data in development?",
      answer: "Real user data contains Personally Identifiable Information (PII). Moving this data to developer machines or staging servers vastly increases the risk of data breaches, which can result in severe legal penalties and loss of customer trust."
    }
  ],

  relatedTools: [
    { name: "UUID Generator", slug: "uuid-generator" },
    { name: "Password Generator", slug: "password-generator" },
    { name: "Hash Generator", slug: "hash-generator" },
    { name: "JSON Formatter", slug: "json-formatter" },
    { name: "Lorem Ipsum Generator", slug: "lorem-ipsum-generator" }
  ]
};
