import { ToolConfig } from './types';

export const sqlFormatterConfig: ToolConfig = {
  slug: "sql-formatter",
  title: "SQL Formatter & Beautifier",
  shortDescription: "Format, beautify, minify, and validate SQL queries instantly. Supports MySQL, PostgreSQL, SQL Server, Oracle, SQLite, BigQuery, Snowflake, and MariaDB with syntax highlighting, query analysis, diff comparison, and format presets — all client-side.",
  category: "Text & Formatting",
  keywords: [
    "sql formatter", "sql beautifier", "sql pretty print", "sql minifier", "format sql online",
    "sql parser", "sql validator", "beautify sql", "minify sql", "sql syntax checker",
    "format sql", "clean sql", "sql to single line", "online sql editor",
    "sql formatting tool", "sql query formatter", "sql code beautifier", "sql indent",
    "mysql formatter", "postgresql formatter", "sql server formatter", "oracle sql formatter",
    "sqlite formatter", "bigquery formatter", "snowflake sql formatter", "mariadb formatter",
    "sql keyword uppercase", "sql style guide", "sql format presets", "sql diff checker",
    "sql query analysis", "sql readability", "sql complexity", "free sql formatter"
  ],

  longDescription: `
## What Is a SQL Formatter?

A **SQL Formatter** (also called a SQL Beautifier or SQL Pretty Printer) is a developer tool that automatically restructures raw, unformatted SQL queries into a clean, consistently indented layout. It inserts proper line breaks, aligns keywords, indents nested clauses, and optionally capitalizes reserved words — all without changing the query's logical meaning or execution behavior.

If you've ever stared at a single-line \`SELECT\` statement that spans 400 characters, you already know why SQL formatting matters. Our SQL Formatter turns that wall of text into a neatly organized, human-readable query in milliseconds.

---

## Why SQL Formatting Matters

SQL is the universal language for interacting with relational databases. Yet despite being one of the most widely used programming languages on earth, SQL has no official formatting standard. Teams adopt ad-hoc conventions, and raw queries — whether generated by ORMs, exported from database consoles, or copy-pasted from Stack Overflow — are almost never pre-formatted.

Unformatted SQL introduces real risks:

- **Debugging difficulty**: A \`WHERE\` clause buried inside a 200-character line is easy to overlook, leading to data bugs that slip through code review.
- **Collaboration friction**: When team members use inconsistent styles, pull request diffs become noisy with whitespace changes mixed into logic changes.
- **Maintenance cost**: Six months from now, the developer reading your query (which might be you) will struggle to understand its intent if the structure is invisible.

Consistently formatted SQL eliminates these problems. It makes queries self-documenting, reduces onboarding time for new team members, and turns code review from a chore into a productive conversation.

---

## Benefits of Readable SQL

Properly formatted SQL delivers measurable benefits across the development lifecycle:

1. **Faster debugging** — Indented \`JOIN\` chains and aligned \`CASE WHEN\` blocks let you visually trace data flow, spot missing conditions, and isolate errors in seconds rather than minutes.
2. **Cleaner code reviews** — When formatting is consistent, reviewers can focus on logic, not layout. Diffs show actual changes, not whitespace noise.
3. **Better documentation** — Well-formatted queries serve as living documentation. A structured \`CREATE VIEW\` statement communicates business rules more effectively than a paragraph of prose.
4. **Reduced onboarding time** — New engineers can read the codebase faster when every query follows the same visual pattern.
5. **Fewer production incidents** — A misplaced \`AND\` vs \`OR\` in a \`WHERE\` clause is obvious in formatted SQL. In a single-line query, it's invisible.

---

## SQL Beautification Best Practices

While there is no universally mandated SQL style, the following conventions are widely adopted in professional environments:

### Keyword Capitalization
Capitalize SQL reserved words (\`SELECT\`, \`FROM\`, \`WHERE\`, \`JOIN\`, \`GROUP BY\`, etc.) to visually separate them from column names and table aliases. This is the single most impactful formatting rule for readability.

### Clause-per-Line
Place each major clause (\`SELECT\`, \`FROM\`, \`WHERE\`, \`GROUP BY\`, \`ORDER BY\`, \`HAVING\`, \`LIMIT\`) on its own line. This creates a vertical "table of contents" for the query.

### Indentation for Nested Logic
Indent subqueries, \`CASE\` expressions, and \`JOIN\` conditions relative to their parent clause. Use consistent indentation — either 2 spaces, 4 spaces, or tabs — throughout your project.

### Comma Placement
Place commas at the end of each line (trailing commas) or at the beginning (leading commas). Pick one and stick with it. Trailing commas are more common; leading commas make it easier to comment out columns.

### Alias Alignment
Align table aliases vertically when you have multiple \`JOIN\` clauses. This transforms a dense block of text into a scannable table.

---

## SQL Indentation Guidelines

Effective indentation creates a visual hierarchy that mirrors the logical structure of your query:

- **Top-level clauses** (\`SELECT\`, \`FROM\`, \`WHERE\`) start at column 0.
- **Column lists** are indented one level under \`SELECT\`.
- **JOIN conditions** (\`ON\`) are indented one level under their \`JOIN\`.
- **Subqueries** are indented one level inside parentheses.
- **CASE expressions** have \`WHEN\`/\`THEN\` indented one level, \`END\` aligned with \`CASE\`.
- **CTEs** (\`WITH\` clauses) have their body indented one level.

This formatter lets you choose between 2-space, 4-space, and tab indentation to match your team's convention.

---

## Common SQL Formatting Mistakes

Even experienced developers make these formatting errors:

1. **Mixing tabs and spaces** — Pick one and enforce it with a formatter. Mixing causes alignment to break across editors.
2. **Inconsistent keyword case** — Using \`select\` in one query and \`SELECT\` in another creates visual noise.
3. **No line breaks before JOIN** — Cramming \`INNER JOIN ... ON ...\` onto the same line as \`FROM\` hides the join structure.
4. **Deeply nested subqueries without indentation** — If you can't tell where a subquery starts and ends, neither can your reviewer.
5. **Overly long lines** — Lines exceeding 120 characters force horizontal scrolling and hide logic off-screen.

---

## SQL Formatting for Teams

When a team adopts a shared SQL style, the benefits compound:

- **Automated enforcement** — Use this formatter as part of your development workflow. Format queries before committing them, just as you'd run Prettier on JavaScript or Black on Python.
- **Reduced merge conflicts** — Consistent formatting means two developers editing the same stored procedure won't create spurious diff noise.
- **Style guide compliance** — Define presets (Compact, Readable, Enterprise) that map to your organization's SQL style guide, then share them across the team.

---

## SQL Formatting for Debugging

Formatting is one of the most effective debugging tools available. When a query returns unexpected results:

1. **Format the query** — Expose its structure.
2. **Read the WHERE clause** — Are all conditions correct? Is \`AND\` vs \`OR\` grouping right?
3. **Trace the JOINs** — Are you joining on the right keys? Is an unintended cross join creating row explosion?
4. **Check the GROUP BY** — Are all non-aggregated columns included?
5. **Examine subqueries** — Run each subquery independently to verify intermediate results.

A properly formatted query makes each of these steps trivial. An unformatted query makes them nearly impossible.

---

## Difference Between Minifying and Beautifying SQL

**Beautifying** (formatting) adds whitespace, line breaks, and indentation to make SQL human-readable. Use it during development, code review, and debugging.

**Minifying** (compressing) removes all unnecessary whitespace, reducing the query to a single dense line. Use it when:
- Embedding SQL in application code where string size matters
- Storing queries in configuration files with line-length constraints
- Transmitting queries over networks where payload size is a concern

Both operations preserve the query's logical meaning. Neither changes how the database executes the query. This tool supports both directions — beautify for humans, minify for machines.

---

## SQL Formatter Use Cases

This tool serves a wide range of professionals:

- **Backend developers** formatting queries generated by ORMs like Hibernate, SQLAlchemy, or Prisma
- **Data analysts** cleaning up ad-hoc queries from database consoles
- **Database administrators** reviewing stored procedures and migration scripts
- **DevOps engineers** formatting SQL embedded in CI/CD pipeline configurations
- **Technical writers** preparing SQL examples for documentation
- **Students** learning SQL syntax by seeing properly structured queries

---

## SQL Style Guide Concepts

A comprehensive SQL style guide typically covers:

- Keyword capitalization policy
- Indentation size and type (spaces vs tabs)
- Maximum line length
- Comma placement (leading vs trailing)
- Alias conventions (\`AS\` keyword required or optional)
- Subquery formatting
- Comment style (inline vs block)
- Naming conventions for tables, columns, and aliases

This formatter gives you control over the most impactful settings — indentation, keyword case, and dialect — while preserving your query's comments and structure.

---

## Query Optimization and Readability

While formatting doesn't change query performance, it dramatically improves your ability to *identify* performance problems. A formatted query reveals:

- Missing indexes (visible in exposed \`WHERE\` and \`JOIN ON\` columns)
- Unnecessary subqueries that could be rewritten as \`JOIN\`s
- \`SELECT *\` anti-patterns hidden in dense one-liners
- Cartesian products from missing \`ON\` conditions
- Redundant \`DISTINCT\` or \`GROUP BY\` clauses

The first step in query optimization is always understanding the query. Formatting is how you get there.
  `,

  features: [
    "Instant SQL beautification with configurable indentation (2 spaces, 4 spaces, or tabs)",
    "SQL Minification to compress queries and reduce string size",
    "Multiple SQL dialect support: MySQL, PostgreSQL, SQL Server, Oracle, SQLite, BigQuery, Snowflake, MariaDB",
    "Professional code editor with full SQL syntax highlighting (Monaco Editor)",
    "SQL keyword case control: UPPERCASE, lowercase, or preserve original",
    "Format presets: Compact, Readable, Enterprise, PostgreSQL Style, MySQL Style",
    "Real-time query analysis: complexity, keyword count, JOIN count, subquery count",
    "Side-by-side SQL diff comparison with added/removed/changed highlighting",
    "Example queries: SELECT, JOIN, Aggregation, Stored Procedure, Complex Nested",
    "File upload and .sql download capabilities",
    "Auto-save with localStorage session persistence",
    "Undo/Redo support and Word Wrap toggle",
    "Dark mode and light mode support",
    "Keyboard accessible with ARIA labels",
    "100% Client-side processing for absolute data privacy and security"
  ],

  useCases: [
    "Formatting complex ORM-generated SQL queries for debugging and code review",
    "Cleaning up ad-hoc queries from database consoles like pgAdmin, MySQL Workbench, or SSMS",
    "Minifying SQL strings before embedding them in application configuration files",
    "Comparing original and formatted SQL side-by-side to verify formatting didn't change logic",
    "Analyzing query complexity and structure before performance optimization",
    "Standardizing SQL style across a development team using consistent format presets",
    "Preparing SQL examples for technical documentation and blog posts",
    "Learning SQL syntax by formatting example queries and studying the structure"
  ],

  howToSteps: [
    "Paste your raw or minified SQL into the editor on the left, or use the 'Upload' button to load a .sql file.",
    "Select your target SQL dialect (MySQL, PostgreSQL, etc.) from the dialect dropdown.",
    "Choose a format preset or configure indentation and keyword case manually.",
    "Click 'Format' to beautify or 'Minify' to compress the SQL.",
    "Review the formatted output in the right panel. Use the 'Analysis' tab to see query statistics.",
    "Switch to 'Diff' mode to compare original vs formatted SQL side-by-side.",
    "Try 'Example Queries' to load sample SQL for testing.",
    "Copy or download the output using the toolbar buttons."
  ],

  examples: [
    {
      title: "Beautify a SELECT Query",
      description: "Format a single-line SELECT into readable, indented SQL.",
      input: "SELECT u.id, u.name, u.email, o.total FROM users u INNER JOIN orders o ON u.id = o.user_id WHERE o.total > 100 AND u.active = 1 ORDER BY o.total DESC LIMIT 50;",
      output: `SELECT\n  u.id,\n  u.name,\n  u.email,\n  o.total\nFROM\n  users u\n  INNER JOIN orders o ON u.id = o.user_id\nWHERE\n  o.total > 100\n  AND u.active = 1\nORDER BY\n  o.total DESC\nLIMIT\n  50;`
    },
    {
      title: "Format a Complex JOIN Query",
      description: "Properly indent multi-table JOINs with conditions.",
      input: "SELECT p.name, c.category_name, SUM(oi.quantity * oi.price) as revenue FROM products p JOIN categories c ON p.category_id = c.id JOIN order_items oi ON p.id = oi.product_id JOIN orders o ON oi.order_id = o.id WHERE o.created_at >= '2024-01-01' GROUP BY p.name, c.category_name HAVING SUM(oi.quantity * oi.price) > 1000 ORDER BY revenue DESC;",
      output: `SELECT\n  p.name,\n  c.category_name,\n  SUM(oi.quantity * oi.price) AS revenue\nFROM\n  products p\n  JOIN categories c ON p.category_id = c.id\n  JOIN order_items oi ON p.id = oi.product_id\n  JOIN orders o ON oi.order_id = o.id\nWHERE\n  o.created_at >= '2024-01-01'\nGROUP BY\n  p.name,\n  c.category_name\nHAVING\n  SUM(oi.quantity * oi.price) > 1000\nORDER BY\n  revenue DESC;`
    }
  ],

  faq: [
    {
      question: "What is SQL formatting?",
      answer: "SQL formatting is the process of restructuring SQL queries with proper indentation, line breaks, and keyword capitalization to improve readability. It does not change the query's logic or execution behavior — only its visual presentation. A well-formatted query is easier to read, debug, review, and maintain."
    },
    {
      question: "Is this SQL formatter free?",
      answer: "Yes, this SQL formatter is completely free to use with no limits. There are no sign-ups, no usage caps, and no premium tiers. You can format as many queries as you need, of any size, in any supported dialect."
    },
    {
      question: "Does this tool support PostgreSQL?",
      answer: "Yes. This formatter supports PostgreSQL along with MySQL, SQL Server, Oracle SQL, SQLite, MariaDB, BigQuery, and Snowflake. Select your target dialect from the dropdown to get dialect-aware formatting with the correct keyword handling."
    },
    {
      question: "Can I beautify large SQL queries?",
      answer: "Yes. The formatter is optimized for performance with debounced processing and efficient rendering. It handles large queries including stored procedures, complex CTEs, and multi-hundred-line scripts smoothly without freezing the UI."
    },
    {
      question: "Is my SQL processed locally?",
      answer: "Yes, absolutely. All formatting, minification, validation, and analysis are performed entirely in your web browser using client-side JavaScript. Your SQL queries are never sent to any server. This ensures complete privacy and security for sensitive database queries."
    },
    {
      question: "Can this tool validate SQL syntax?",
      answer: "Yes. The formatter includes a real-time validation system that detects common syntax issues such as unmatched parentheses, unclosed quotes, missing semicolons, and invalid keyword usage. Validation messages appear instantly as you type."
    },
    {
      question: "Does the formatter execute SQL queries?",
      answer: "No. This is a formatting-only tool. It does not connect to any database, does not execute queries, and does not process any data. It only restructures the visual layout of your SQL text. Your queries are never run against any database engine."
    }
  ],

  relatedTools: [
    { name: "JSON Formatter", slug: "json-formatter" },
    { name: "HTML Formatter", slug: "html-formatter" },
    { name: "CSS Beautifier", slug: "css-beautifier" },
    { name: "JavaScript Beautifier", slug: "js-beautifier" },
    { name: "XML Formatter", slug: "xml-formatter" },
    { name: "Markdown Previewer", slug: "markdown-previewer" }
  ]
};
