import { ToolConfig } from './types';

export const uuidGeneratorConfig: ToolConfig = {
  slug: "uuid-generator",
  title: "UUID Generator",
  shortDescription: "Generate random, unique, and cryptographically secure UUIDs (v1, v4, v6, v7). Instantly create individual or bulk UUIDs for your databases, APIs, and microservices.",
  category: "Generators",
  keywords: ["UUID generator", "GUID generator", "UUID v4", "UUID v7", "bulk UUID", "generate UUIDs", "online UUID tool", "database IDs", "unique identifier"],
  
  longDescription: `
A **Universally Unique Identifier (UUID)** is a 128-bit number used to uniquely identify information in computer systems. Also known as Globally Unique Identifiers (GUIDs) within the Microsoft ecosystem, UUIDs are heavily utilized in software development, database architecture, and microservices to ensure absolute uniqueness across distributed systems without needing a central coordinating authority.

Our **Production-Grade UUID Generator** allows you to instantly generate cryptographically secure UUIDs. It supports generating multiple versions including **UUID v1**, **UUID v4**, **UUID v6**, and **UUID v7**, ensuring you have the exact formatting protocol required for your architectural needs.

### Why Use UUIDs Instead of Auto-Incrementing IDs?

In traditional monolithic relational databases (like older versions of MySQL or PostgreSQL), using auto-incrementing integer IDs (e.g., 1, 2, 3...) for primary keys was the standard. While highly efficient for simple applications, auto-incrementing IDs present massive scalability and security challenges in modern cloud architectures.

#### 1. Security and "Guessability" (Insecure Direct Object Reference)
Sequential IDs expose the size, growth rate, and internal structure of your data. If a new user signs up and is assigned user ID 1050, they immediately know you have 1,049 other users. More dangerously, if your API uses sequential IDs (e.g., \`/api/users/1050/profile\`), a malicious actor can simply write a script to iterate through \`1051\`, \`1052\`, \`1053\` and scrape all your user data—a vulnerability known as Insecure Direct Object Reference (IDOR). UUIDs completely eliminate this risk because they are random, non-sequential, and mathematically impossible to guess.

#### 2. Distributed Systems and Microservices
Modern applications are rarely hosted on a single server. They run on globally distributed microservices, Serverless functions, and clustered databases (like Cassandra, DynamoDB, or CockroachDB). In a distributed environment where multiple instances are writing to the database concurrently, generating sequential IDs requires a centralized "lock" to prevent two servers from claiming the same ID. This creates a massive performance bottleneck. UUIDs solve this: any node, anywhere in the world, can generate a UUID locally and write it to the database with a virtually 0% chance of colliding with an ID generated by another node.

#### 3. Offline Data Creation and Syncing
If you are building an offline-first mobile application, users might create records (like taking a photo or writing a note) while disconnected from the internet. If you rely on the database to assign an ID, the app cannot finalize the record until it reconnects. With UUIDs, the mobile client can generate the ID locally, save the record to the local device storage, and seamlessly sync it with the server later without any ID collision conflicts.

### Understanding the Different UUID Versions

Not all UUIDs are created equal. The Internet Engineering Task Force (IETF) has defined several versions (RFC 4122 and recent updates), each serving a specific use case based on how the 128 bits are generated.

#### UUID Version 1 (Time & MAC Address Based)
UUID v1 is generated using a combination of the current timestamp (measured in 100-nanosecond intervals since October 15, 1582) and the MAC address of the computer generating it. 
- **Pros:** Because it includes a timestamp, v1 UUIDs are somewhat sequential, which can be slightly better for database indexing than pure randomness.
- **Cons:** It exposes the MAC address of the host machine, which is a major privacy and security concern in many modern networking contexts. It is rarely used in new applications today.

#### UUID Version 4 (Fully Random)
This is by far the most common version in use today. UUID v4 is generated using cryptographically secure random number generators (CSPRNG). 
- **The Math:** A v4 UUID has 122 randomly generated bits. This means there are $2^{122}$ (or $5.3 \\times 10^{36}$) possible values. To put that into perspective, you would need to generate 1 billion UUIDs every second for 85 years to have a 50% chance of a single collision. 
- **Pros:** Unmatched randomness, privacy, and zero chance of guessing.
- **Cons:** Because they are entirely random, they fragment database indexes (specifically B-Tree indexes), which can slow down insert performance in massive databases.

#### UUID Version 6 and Version 7 (Time-Sorted Random)
To solve the database indexing performance issues of v4, the IETF introduced new standards: v6 and v7.
- **UUID v6:** Retains the timestamp logic of v1 but rearranges the bit order so that the most significant bits of the time are at the front. This makes the UUIDs sequentially sortable by time.
- **UUID v7 (The Modern Standard):** Uses the widely adopted Unix Epoch timestamp (milliseconds since 1970) for the first 48 bits, followed by 74 bits of cryptographic randomness. 
- **Why v7 is the future:** UUID v7 gives you the best of both worlds. It is entirely random and anonymous (like v4), but because it is prefixed with a timestamp, it is chronologically sortable. When you insert v7 UUIDs into a PostgreSQL or MySQL database, they append to the end of the index cleanly, resulting in dramatically faster database performance compared to v4.

### The Standard Format

Regardless of the version, a UUID is represented as a 36-character string (32 hexadecimal digits and 4 hyphens) grouped in an \`8-4-4-4-12\` format. 
Example: \`123e4567-e89b-12d3-a456-426614174000\`

Our tool allows you to format this output exactly how you need it: you can remove the hyphens, convert the characters to uppercase, or wrap them in braces (which is often required in legacy Microsoft .NET and SQL Server environments).

### Bulk Generation for Developers

While generating a single UUID is useful for testing an API endpoint in Postman, developers frequently need thousands of IDs to seed development databases, run load tests, or migrate legacy data. 
Our tool includes a high-performance **Bulk Generation Mode**. You can instantly generate up to 10,000 UUIDs at a time. The output can be easily copied to your clipboard or exported as a text file for immediate use in your scripts.

### 100% Secure Client-Side Execution

When generating IDs for production systems—especially UUIDs used as API keys, session tokens, or password reset links—security is paramount. 
Our generator executes 100% locally in your web browser using the native \`crypto.randomUUID()\` and \`crypto.getRandomValues()\` Web APIs. We do not generate the UUIDs on our server, and we do not log them. The IDs you generate are cryptographically secure, completely private, and known only to you.

### Conclusion

Whether you are designing the architecture for a globally distributed microservices platform, seeding a local test database, or just need a quick, unguessable identifier for a script, our UUID Generator is the perfect tool. Bookmark this page for instant access to secure, offline-capable, and multi-version UUID generation.
  `,

  features: [
    "Support for multiple UUID versions: v1, v4, v6, and v7",
    "Instantly generate single or bulk UUIDs (up to 10,000 at once)",
    "Export generated UUIDs to JSON, CSV, or TXT",
    "Custom formatting options: uppercase, lowercase, remove hyphens, add braces/quotes",
    "Developer utility snippets for generating UUIDs in multiple programming languages",
    "Real-time UUID validation and version detection",
    "100% Client-side generation (Secure & Private)",
    "Local history system to restore recently generated UUIDs"
  ],

  useCases: [
    "Generating random primary keys for database records (PostgreSQL, MySQL, MongoDB)",
    "Creating unique correlation IDs for tracing distributed microservices logs",
    "Mocking data for API endpoints and testing environments",
    "Generating secure, unguessable IDs for public-facing URLs and resources",
    "Creating unique identifiers for client-side offline data creation",
    "Validating external UUIDs to ensure they meet format specifications"
  ],

  howToSteps: [
    "Select the UUID version you want to generate (v4 is the default and most common).",
    "Choose how many UUIDs you need by clicking one of the bulk options or entering a custom amount.",
    "Toggle any formatting options, such as uppercase or stripping hyphens.",
    "Click the 'Generate' button (or it will generate automatically on load).",
    "Use the copy buttons to copy a single UUID, or copy all of them as an array, CSV, or raw list.",
    "If you generated a large batch, use the 'Download' button to export them to a file.",
    "Check the 'Developer Snippets' tab to see how to implement UUID generation in your own code.",
    "Use the 'Validator' tab to paste an existing UUID and verify its format and version."
  ],

  examples: [
    {
      title: "Standard UUID v4",
      description: "The default format for a randomly generated UUID v4.",
      input: "Generate 1 UUID v4",
      output: "123e4567-e89b-12d3-a456-426614174000"
    },
    {
      title: "No Hyphens (Uppercase)",
      description: "UUID formatted without hyphens and converted to uppercase.",
      input: "Generate UUID (No Hyphens, Uppercase)",
      output: "123E4567E89B12D3A456426614174000"
    },
    {
      title: "JSON Array Format",
      description: "Generating a bulk list of UUIDs formatted as a JSON array.",
      input: "Generate 3 UUIDs -> Copy as JSON Array",
      output: `[
  "550e8400-e29b-41d4-a716-446655440000",
  "6ba7b810-9dad-11d1-80b4-00c04fd430c8",
  "6ba7b811-9dad-11d1-80b4-00c04fd430c8"
]`
    }
  ],

  faq: [
    {
      question: "What does UUID stand for?",
      answer: "UUID stands for Universally Unique Identifier. It is a 128-bit label used to uniquely identify information in computer systems. In the Microsoft ecosystem, they are often referred to as GUIDs (Globally Unique Identifiers)."
    },
    {
      question: "Are UUIDs completely unique? Can they collide?",
      answer: "While mathematically possible, a collision (generating the exact same UUID twice) is practically impossible for UUID v4. With $2^{122}$ (approx 5.3 x 10^36) possible variations, you could generate 1 billion UUIDs per second for 85 years, and the probability of a single collision would still be around 50%."
    },
    {
      question: "What is the difference between UUID v4 and v7?",
      answer: "UUID v4 is completely random. UUID v7 combines a Unix timestamp (with millisecond precision) with random data. Because v7 starts with a timestamp, the generated UUIDs are naturally sorted by time, which makes them much more efficient for database indexing than fully random v4 UUIDs."
    },
    {
      question: "Is this tool secure?",
      answer: "Yes. All UUIDs are generated directly inside your web browser using modern web cryptography APIs. We do not track, store, or transmit the UUIDs you generate over the network."
    },
    {
      question: "Should I use UUIDs or Auto-Incrementing IDs?",
      answer: "Auto-incrementing IDs (1, 2, 3...) are simple and efficient but expose your data size and can be easily guessed. They also create bottlenecks in distributed databases. UUIDs hide your data scale, cannot be guessed, and can be generated anywhere independently, making them the standard choice for modern distributed applications."
    },
    {
      question: "How long is a UUID?",
      answer: "A standard string representation of a UUID contains 36 characters: 32 hexadecimal digits and 4 hyphens, formatted as 8-4-4-4-12."
    },
    {
      question: "What does a UUID v4 look like?",
      answer: "A UUID v4 looks like this: xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx. Notice the '4' in the third section, indicating the version. The 'y' will always be 8, 9, a, or b."
    }
  ],

  relatedTools: [
    { name: "Hash Generator", slug: "hash-generator" },
    { name: "Password Generator", slug: "password-generator" },
    { name: "JSON Formatter", slug: "json-formatter" },
    { name: "Base64 Encode", slug: "base64-encode" }
  ]
};
