import { Metadata } from 'next';
import { Link as CustomLink } from '@/i18n/routing';
import { setRequestLocale } from 'next-intl/server';
import { AlertTriangle, Scale, Stethoscope, LineChart, FileText } from 'lucide-react';

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> {
  const { locale } = await params;
  const { getCanonicalAndAlternates } = await import('@/lib/utils/seoUtils');

  return {
    title: 'Medical & Financial Disclaimer | Nexus Tools Platform',
    description: 'Read the Nexus Tools Medical and Financial Disclaimer. All tools and calculators on this platform are for educational and informational purposes only.',
    alternates: getCanonicalAndAlternates('/disclaimer', locale),
  };
}

export default async function DisclaimerPage({ params }: { params: Promise<{ locale: string }> }) {
  const resolvedParams = await params;
  setRequestLocale(resolvedParams.locale);
  return (
    <main className="w-full max-w-[1200px] mx-auto px-4 sm:px-6 lg:px-8 py-12 lg:py-20 font-sans">
      
      {/* Breadcrumbs */}
      <nav aria-label="Breadcrumb" className="text-sm text-slate-500 dark:text-slate-400 mb-8">
        <ol className="flex items-center space-x-2">
          <li>
            <CustomLink href="/" className="hover:text-[#518231] dark:hover:text-[#6fa844] hover:underline transition-colors">Home</CustomLink>
          </li>
          <li><span className="mx-1 text-slate-400 dark:text-slate-600">/</span></li>
          <li aria-current="page" className="text-slate-700 dark:text-slate-300 font-medium">Disclaimer</li>
        </ol>
      </nav>

      <header className="mb-14 border-b border-slate-200 dark:border-slate-800 pb-10">
        <div className="flex items-center gap-4 mb-6">
          <div className="bg-amber-100 dark:bg-amber-900/30 p-3 rounded-xl text-amber-700 dark:text-amber-400">
            <AlertTriangle size={32} />
          </div>
          <h1 className="text-4xl md:text-5xl font-extrabold text-slate-900 dark:text-white tracking-tight">Medical & Financial Disclaimer</h1>
        </div>
        <p className="text-xl text-slate-600 dark:text-slate-400 leading-relaxed max-w-3xl">
          The tools, calculators, and content provided on Nexus Calculator are strictly for educational and informational purposes. They do not constitute professional medical, financial, legal, or tax advice.
        </p>
      </header>

      <article className="prose prose-slate dark:prose-invert prose-lg max-w-none">
        
        <div className="bg-amber-50 dark:bg-amber-900/10 border-l-4 border-amber-500 p-6 rounded-r-xl my-8 not-prose">
          <h3 className="font-bold text-slate-900 dark:text-white text-xl mb-3 flex items-center gap-2">
            <Scale className="text-amber-500" size={24} /> General Disclaimer
          </h3>
          <p className="text-slate-700 dark:text-slate-300 leading-relaxed m-0">
            By using Nexus Calculator (nexuscalculator.net), you acknowledge and agree that all results generated by our calculators are estimates based on standard mathematical formulas and the input variables you provide. We make no warranties, express or implied, regarding the accuracy, completeness, or suitability of the calculations for your specific personal, business, or legal requirements.
          </p>
        </div>

        <h2 className="flex items-center gap-3 text-2xl font-bold mt-12 mb-6">
          <LineChart className="text-blue-500" size={28} /> Financial & Investment Tools
        </h2>
        <p>
          Our financial tools—including but not limited to Mortgage Calculators, Loan Calculators, ROI Estimators, and Tax Calculators—are designed to give you a rough approximation of potential financial scenarios. 
        </p>
        <ul>
          <li><strong>Not Financial Advice:</strong> We are not a registered investment advisor, broker-dealer, or tax professional.</li>
          <li><strong>Market Volatility:</strong> Actual interest rates, loan terms, property taxes, insurance premiums, and investment returns will vary based on market conditions, your credit score, and decisions made by third-party financial institutions.</li>
          <li><strong>Consult a Professional:</strong> Always consult with a certified financial planner (CFP), accountant (CPA), or legal counsel before making any significant financial decisions, signing loan documents, or investing capital.</li>
        </ul>

        <h2 className="flex items-center gap-3 text-2xl font-bold mt-12 mb-6">
          <Stethoscope className="text-rose-500" size={28} /> Health, Fitness & Medical Tools
        </h2>
        <p>
          Our health and fitness tools—such as BMI Calculators, BMR Calculators, Calorie Counters, and Pregnancy Calculators—utilize generalized statistical formulas to provide broad fitness metrics.
        </p>
        <ul>
          <li><strong>Not Medical Advice:</strong> The information generated by these tools is not a substitute for professional medical advice, diagnosis, or treatment.</li>
          <li><strong>Individual Variability:</strong> Formulas like BMI do not account for muscle mass, bone density, age-specific factors, or underlying health conditions.</li>
          <li><strong>Consult a Doctor:</strong> Never disregard professional medical advice or delay in seeking it because of something you have read or calculated on this website. Always consult with a licensed physician or healthcare provider before beginning a new diet, exercise program, or making health-related decisions.</li>
        </ul>

        <h2 className="flex items-center gap-3 text-2xl font-bold mt-12 mb-6">
          <FileText className="text-slate-500" size={28} /> Limitation of Liability
        </h2>
        <p>
          Under no circumstances shall Nexus Calculator, its developers, affiliates, or partners be liable for any direct, indirect, incidental, consequential, or special damages arising out of or in any way connected with your use of the tools and information provided on this platform. You assume full responsibility and risk for your use of the site.
        </p>

      </article>

    </main>
  );
}
