const fs = require('fs');

const missing = [
  "Pension Calculator",
  "Credit Card Calculator",
  "Repayment Calculator",
  "IRA Calculator",
  "Auto Lease Calculator",
  "Discount Calculator",
  "Take-Home-Paycheck Calculator",
  "Refinance Calculator",
  "ROI Calculator",
  "Home Equity Loan Calculator",
  "Payback Period Calculator",
  "One Rep Max Calculator",
  "Protein Calculator",
  "TDEE Calculator",
  "Conception Calculator",
  "GFR Calculator",
  "Body Surface Area Calculator",
  "Anorexic BMI Calculator",
  "Overweight Calculator",
  "Pregnancy Weight Gain Calculator",
  "Army Body Fat Calculator",
  "Lean Body Mass Calculator",
  "Calories Burned Calculator",
  "Target Heart Rate Calculator",
  "Fat Intake Calculator",
  "Period Calculator",
  "Body Type Calculator",
  "BAC Calculator",
  "Weight Watcher Points Calculator",
  "Slope Calculator",
  "Area Calculator",
  "Probability Calculator",
  "Mean, Median, Mode, Range Calculator",
  "Z-score Calculator",
  "Ratio Calculator",
  "Circle Calculator",
  "Pythagorean Theorem Calculator",
  "Root Calculator",
  "Greatest Common Factor Calculator",
  "Rounding Calculator",
  "Prime Factorization Calculator",
  "Basic Calculator",
  "Average Calculator",
  "Number Sequence Calculator",
  "Exponent Calculator",
  "Hex Calculator",
  "Quadratic Formula Calculator",
  "Log Calculator",
  "Sample Size Calculator",
  "Permutation and Combination Calculator",
  "Confidence Interval Calculator",
  "Distance Calculator",
  "Surface Area Calculator",
  "Right Triangle Calculator",
  "Least Common Multiple Calculator",
  "Factor Calculator",
  "Matrix Calculator",
  "Big Number Calculator",
  "Common Factor Calculator",
  "Long Division Calculator",
  "Voltage Drop Calculator",
  "Square Footage Calculator",
  "Time Zone Calculator",
  "GDP Calculator",
  "Horsepower Calculator",
  "Stair Calculator",
  "Ohms Law Calculator",
  "Shoe Size Conversion",
  "Mileage Calculator",
  "Mass Calculator",
  "Speed Calculator",
  "Molecular Weight Calculator",
  "Golf Handicap Calculator",
  "Tire Size Calculator",
  "Tile Calculator",
  "Gravel Calculator",
  "Heat Index Calculator",
  "Bandwidth Calculator",
  "URL Encode / Decode",
  "Day Counter",
  "Bra Size Calculator",
  "Dice Roller",
  "Fuel Cost Calculator",
  "BTU Calculator",
  "Time Card Calculator",
  "Love Calculator",
  "Gas Mileage Calculator",
  "Engine Horsepower Calculator",
  "Resistor Calculator",
  "Electricity Calculator",
  "Tip Calculator",
  "Density Calculator",
  "Weight Calculator",
  "Molarity Calculator",
  "Roman Numeral Converter",
  "Sleep Calculator",
  "Roofing Calculator",
  "Mulch Calculator",
  "Wind Chill Calculator",
  "Dew Point Calculator",
  "Base64 Encode / Decode",
  "Time Duration Calculator",
  "Day of the Week Calculator",
  "Mortgage Calculator for Your Site",
  "Scientific Calculator for Your Site",
  "Concrete Calculator for Your Site",
  "Math Calculator for Your Site",
  "Love Calculator for Your Site",
  "JSON Validator",
  "CSS Minifier",
  "JS Minifier",
  "HTML Minifier",
  "Color Extractor",
  "Image Upscaler"
];

let content = fs.readFileSync('lib/data/sitemapData.ts', 'utf8');

for (const link of missing) {
  const escapedLink = link.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  
  // 1. Remove from object arrays: { name: "Link Name", desc: "..." },
  const regex2 = new RegExp(`\\s*\\{[^{]*name:\\s*["']${escapedLink}["'][^}]*\\},?`, 'g');
  content = content.replace(regex2, '');

  // 2. Remove from string arrays: "Link Name", or "Link Name"
  const regex1 = new RegExp(`\\s*["']${escapedLink}["'](?:,)?`, 'g');
  content = content.replace(regex1, '');
}

// Cleanup trailing commas that might have been left
content = content.replace(/,\s*,/g, ',');
content = content.replace(/\[\s*,/g, '[');
content = content.replace(/,\s*\]/g, ']');

fs.writeFileSync('lib/data/sitemapData.ts', content, 'utf8');
console.log("Cleanup complete!");
